// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC1yxaLebLeCeMqMYM-Eby4IwjjcFyee0',
    appId: '1:489007257025:web:d5119ec22775084d7e0b40',
    messagingSenderId: '489007257025',
    projectId: 'fir-333d8',
    authDomain: 'fir-333d8.firebaseapp.com',
    storageBucket: 'fir-333d8.appspot.com',
    measurementId: 'G-48B35PL9YX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXjjHM9mauMfrysyZHIlx1HeE-F5HgeD0',
    appId: '1:489007257025:android:5a53caf3250084b17e0b40',
    messagingSenderId: '489007257025',
    projectId: 'fir-333d8',
    storageBucket: 'fir-333d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAapeAVu60VoZFAALLd2yB-sVa6lYNwRns',
    appId: '1:489007257025:ios:ce8c505a4196ef2b7e0b40',
    messagingSenderId: '489007257025',
    projectId: 'fir-333d8',
    storageBucket: 'fir-333d8.appspot.com',
    androidClientId:
        '489007257025-13ea851h8al5fefvebldiqun6q08hrli.apps.googleusercontent.com',
    iosClientId:
        '489007257025-a58psehi6jfe9p5bbb7v89vhn2u8p55m.apps.googleusercontent.com',
    iosBundleId: 'com.payaki.payaki',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAapeAVu60VoZFAALLd2yB-sVa6lYNwRns',
    appId: '1:489007257025:ios:ce8c505a4196ef2b7e0b40',
    messagingSenderId: '489007257025',
    projectId: 'fir-333d8',
    storageBucket: 'fir-333d8.appspot.com',
    androidClientId:
        '489007257025-13ea851h8al5fefvebldiqun6q08hrli.apps.googleusercontent.com',
    iosClientId:
        '489007257025-a58psehi6jfe9p5bbb7v89vhn2u8p55m.apps.googleusercontent.com',
    iosBundleId: 'com.payaki.payaki',
  );
}
